# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scout_msgs/ScoutRCState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ScoutRCState(genpy.Message):
  _md5sum = "c78447ebdf8846481ba608e1b4be107c"
  _type = "scout_msgs/ScoutRCState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 swa
uint8 swb
uint8 swc
uint8 swd

int8 stick_right_v
int8 stick_right_h
int8 stick_left_v
int8 stick_left_h
int8 var_a"""
  __slots__ = ['swa','swb','swc','swd','stick_right_v','stick_right_h','stick_left_v','stick_left_h','var_a']
  _slot_types = ['uint8','uint8','uint8','uint8','int8','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       swa,swb,swc,swd,stick_right_v,stick_right_h,stick_left_v,stick_left_h,var_a

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ScoutRCState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.swa is None:
        self.swa = 0
      if self.swb is None:
        self.swb = 0
      if self.swc is None:
        self.swc = 0
      if self.swd is None:
        self.swd = 0
      if self.stick_right_v is None:
        self.stick_right_v = 0
      if self.stick_right_h is None:
        self.stick_right_h = 0
      if self.stick_left_v is None:
        self.stick_left_v = 0
      if self.stick_left_h is None:
        self.stick_left_h = 0
      if self.var_a is None:
        self.var_a = 0
    else:
      self.swa = 0
      self.swb = 0
      self.swc = 0
      self.swd = 0
      self.stick_right_v = 0
      self.stick_right_h = 0
      self.stick_left_v = 0
      self.stick_left_h = 0
      self.var_a = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B5b().pack(_x.swa, _x.swb, _x.swc, _x.swd, _x.stick_right_v, _x.stick_right_h, _x.stick_left_v, _x.stick_left_h, _x.var_a))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.swa, _x.swb, _x.swc, _x.swd, _x.stick_right_v, _x.stick_right_h, _x.stick_left_v, _x.stick_left_h, _x.var_a,) = _get_struct_4B5b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B5b().pack(_x.swa, _x.swb, _x.swc, _x.swd, _x.stick_right_v, _x.stick_right_h, _x.stick_left_v, _x.stick_left_h, _x.var_a))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.swa, _x.swb, _x.swc, _x.swd, _x.stick_right_v, _x.stick_right_h, _x.stick_left_v, _x.stick_left_h, _x.var_a,) = _get_struct_4B5b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B5b = None
def _get_struct_4B5b():
    global _struct_4B5b
    if _struct_4B5b is None:
        _struct_4B5b = struct.Struct("<4B5b")
    return _struct_4B5b
